CREATE TABLE organizer (
  event_year int,
  person_email varchar(32),
  roles varchar(512) NOT NULL,
  PRIMARY KEY (event_year, person_email)
);

CREATE TABLE person (
  email varchar(32) PRIMARY KEY,
  type varchar(32) NOT NULL,
  first_name varchar(32) NOT NULL,
  last_name varchar(32) NOT NULL,
  phone varchar(16),
  department_code varchar(8) NOT NULL
);

CREATE TABLE department (
  code varchar(8) PRIMARY KEY,
  name varchar(64) NOT NULL,
  auh_full_name varchar(32) NOT NULL,
  auh_email varchar(32) NOT NULL,
  college_code varchar(8) NOT NULL
);

CREATE TABLE college (
  code varchar(8) PRIMARY KEY,
  name varchar(64) NOT NULL,
  dean_full_name varchar(32) NOT NULL,
  dean_email varchar(32) NOT NULL,
  dean_first_name varchar(32) NOT NULL
);

CREATE TABLE event (
  year int PRIMARY KEY,
  date date NOT NULL
);

CREATE TABLE person_workshop (
  person_email varchar(32),
  workshop_id int,
  role varchar(32) NOT NULL,
  PRIMARY KEY (person_email, workshop_id)
);

CREATE TABLE workshop (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state varchar(32) NOT NULL,
  title varchar(64) NOT NULL,
  advertisement varchar(512),
  description varchar(1024),
  capacity int,
  computer_needs varchar(128),
  room_needs varchar(128),
  max_repeat int,
  parent_questions varchar(1024),
  other_information varchar(512),
  event_year int NOT NULL,
  room_name varchar(32)
);

CREATE TABLE room (
  name varchar(32) PRIMARY KEY,
  type varchar(32) NOT NULL,
  capacity int NOT NULL,
  notes varchar(64)
);

CREATE TABLE timeslot (
  event_year int,
  id int,
  name varchar(32) NOT NULL,
  beg_time time NOT NULL,
  end_time time NOT NULL,
  PRIMARY KEY (event_year, id)
);

CREATE TABLE workshop_timeslot (
  workshop_id int,
  timeslot_event_year int,
  timeslot_id int,
  PRIMARY KEY (workshop_id, timeslot_event_year, timeslot_id)
);

CREATE TABLE room_feature (
  room_name varchar(32),
  feature_name varchar(32),
  PRIMARY KEY (room_name, feature_name)
);

CREATE TABLE feature (
  name varchar(32) PRIMARY KEY,
  description varchar(128)
);